# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(1095, 764)
        self.centralwidget = QtWidgets.QWidget(dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.studentLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.studentLabel_3.setGeometry(QtCore.QRect(390, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.studentLabel_3.setFont(font)
        self.studentLabel_3.setObjectName("studentLabel_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1071, 621))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.studentTableView = QtWidgets.QTableView(self.tab)
        self.studentTableView.setGeometry(QtCore.QRect(10, 50, 1051, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentTableView.sizePolicy().hasHeightForWidth())
        self.studentTableView.setSizePolicy(sizePolicy)
        self.studentTableView.setObjectName("studentTableView")
        self.printStudents = QtWidgets.QPushButton(self.tab)
        self.printStudents.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.printStudents.setText("")
        self.printStudents.setObjectName("printStudents")
        self.studentLabel_4 = QtWidgets.QLabel(self.tab)
        self.studentLabel_4.setGeometry(QtCore.QRect(440, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.studentLabel_4.setFont(font)
        self.studentLabel_4.setObjectName("studentLabel_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.facultyTableView = QtWidgets.QTableView(self.tab_2)
        self.facultyTableView.setGeometry(QtCore.QRect(10, 50, 1051, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facultyTableView.sizePolicy().hasHeightForWidth())
        self.facultyTableView.setSizePolicy(sizePolicy)
        self.facultyTableView.setObjectName("facultyTableView")
        self.printFaculty = QtWidgets.QPushButton(self.tab_2)
        self.printFaculty.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.printFaculty.setText("")
        self.printFaculty.setObjectName("printFaculty")
        self.studentLabel_5 = QtWidgets.QLabel(self.tab_2)
        self.studentLabel_5.setGeometry(QtCore.QRect(440, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.studentLabel_5.setFont(font)
        self.studentLabel_5.setObjectName("studentLabel_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.timeTableTab = QtWidgets.QWidget()
        self.timeTableTab.setObjectName("timeTableTab")
        self.printTimeTablebtn = QtWidgets.QPushButton(self.timeTableTab)
        self.printTimeTablebtn.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.printTimeTablebtn.setText("")
        self.printTimeTablebtn.setObjectName("printTimeTablebtn")
        self.studentLabel_6 = QtWidgets.QLabel(self.timeTableTab)
        self.studentLabel_6.setGeometry(QtCore.QRect(440, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.studentLabel_6.setFont(font)
        self.studentLabel_6.setObjectName("studentLabel_6")
        self.timeTableView = QtWidgets.QTableView(self.timeTableTab)
        self.timeTableView.setGeometry(QtCore.QRect(10, 50, 1051, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeTableView.sizePolicy().hasHeightForWidth())
        self.timeTableView.setSizePolicy(sizePolicy)
        self.timeTableView.setObjectName("timeTableView")
        self.tabWidget.addTab(self.timeTableTab, "")
        dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(dashboard)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        dashboard.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        dashboard.setMenuBar(self.menubar)
        self.actionStudent = QtWidgets.QAction(dashboard)
        self.actionStudent.setObjectName("actionStudent")
        self.actionFaculty = QtWidgets.QAction(dashboard)
        self.actionFaculty.setObjectName("actionFaculty")
        self.actionExit = QtWidgets.QAction(dashboard)
        self.actionExit.setObjectName("actionExit")
        self.actionStudent_2 = QtWidgets.QAction(dashboard)
        self.actionStudent_2.setStatusTip("")
        self.actionStudent_2.setIconVisibleInMenu(True)
        self.actionStudent_2.setObjectName("actionStudent_2")
        self.actionFaculty_2 = QtWidgets.QAction(dashboard)
        self.actionFaculty_2.setObjectName("actionFaculty_2")
        self.actionExit_toolbar = QtWidgets.QAction(dashboard)
        self.actionExit_toolbar.setObjectName("actionExit_toolbar")
        self.actionActivateUser = QtWidgets.QAction(dashboard)
        self.actionActivateUser.setObjectName("actionActivateUser")
        self.actionActivateUser2 = QtWidgets.QAction(dashboard)
        self.actionActivateUser2.setObjectName("actionActivateUser2")
        self.actionLogout = QtWidgets.QAction(dashboard)
        self.actionLogout.setObjectName("actionLogout")
        self.toolBar.addAction(self.actionStudent_2)
        self.toolBar.addAction(self.actionFaculty_2)
        self.toolBar.addAction(self.actionActivateUser2)
        self.toolBar.addAction(self.actionLogout)
        self.toolBar.addAction(self.actionExit_toolbar)
        self.menuFile.addAction(self.actionStudent)
        self.menuFile.addAction(self.actionFaculty)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionActivateUser)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(dashboard)
        self.tabWidget.setCurrentIndex(1)
        self.actionExit.triggered.connect(dashboard.close)
        self.actionExit_toolbar.triggered.connect(dashboard.close)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Admin Dashboard"))
        self.studentLabel_3.setText(_translate("dashboard", "Admin Dashboard"))
        self.studentLabel_4.setText(_translate("dashboard", "Students"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dashboard", "Students"))
        self.studentLabel_5.setText(_translate("dashboard", "Faculty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dashboard", "Faculty"))
        self.studentLabel_6.setText(_translate("dashboard", "Time Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timeTableTab), _translate("dashboard", "Time Table"))
        self.toolBar.setWindowTitle(_translate("dashboard", "toolBar"))
        self.menuFile.setTitle(_translate("dashboard", "Data Entry Forms"))
        self.menuTools.setTitle(_translate("dashboard", "Tools"))
        self.actionStudent.setText(_translate("dashboard", "Student"))
        self.actionStudent.setShortcut(_translate("dashboard", "Alt+S"))
        self.actionFaculty.setText(_translate("dashboard", "Faculty"))
        self.actionFaculty.setShortcut(_translate("dashboard", "Alt+F"))
        self.actionExit.setText(_translate("dashboard", "Exit"))
        self.actionExit.setShortcut(_translate("dashboard", "Alt+X"))
        self.actionStudent_2.setText(_translate("dashboard", "Student"))
        self.actionStudent_2.setIconText(_translate("dashboard", "Student"))
        self.actionStudent_2.setToolTip(_translate("dashboard", "Add Student"))
        self.actionStudent_2.setShortcut(_translate("dashboard", "Alt+S"))
        self.actionFaculty_2.setText(_translate("dashboard", "Faculty"))
        self.actionFaculty_2.setToolTip(_translate("dashboard", "Add Faculty Member"))
        self.actionFaculty_2.setShortcut(_translate("dashboard", "Alt+F"))
        self.actionExit_toolbar.setText(_translate("dashboard", "Exit"))
        self.actionExit_toolbar.setToolTip(_translate("dashboard", "Exit"))
        self.actionExit_toolbar.setShortcut(_translate("dashboard", "Alt+X"))
        self.actionActivateUser.setText(_translate("dashboard", "Activate User"))
        self.actionActivateUser2.setText(_translate("dashboard", "Activate User"))
        self.actionActivateUser2.setToolTip(_translate("dashboard", "Assign ID, Password"))
        self.actionLogout.setText(_translate("dashboard", "Logout"))


