# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/StudentForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentDetails(object):
    def setupUi(self, StudentDetails):
        StudentDetails.setObjectName("StudentDetails")
        StudentDetails.resize(540, 657)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        StudentDetails.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(StudentDetails)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 60, 311, 562))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.ageSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ageSpinBox.setFont(font)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ageSpinBox)
        self.addressLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.addressLabel)
        self.addressTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.addressTextEdit.setFont(font)
        self.addressTextEdit.setObjectName("addressTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.addressTextEdit)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.maleRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maleRadioButton.sizePolicy().hasHeightForWidth())
        self.maleRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.maleRadioButton.setFont(font)
        self.maleRadioButton.setIconSize(QtCore.QSize(15, 16))
        self.maleRadioButton.setObjectName("maleRadioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(StudentDetails)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.maleRadioButton)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maleRadioButton)
        self.femaleRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.femaleRadioButton.setFont(font)
        self.femaleRadioButton.setObjectName("femaleRadioButton")
        self.buttonGroup_2.addButton(self.femaleRadioButton)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.femaleRadioButton)
        self.courseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.courseLabel.setFont(font)
        self.courseLabel.setObjectName("courseLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.courseLabel)
        self.courseList = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.courseList.setFont(font)
        self.courseList.setObjectName("courseList")
        self.courseList.addItem("")
        self.courseList.addItem("")
        self.courseList.addItem("")
        self.courseList.addItem("")
        self.courseList.addItem("")
        self.courseList.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.courseList)
        self.timeSlotLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.timeSlotLabel.setFont(font)
        self.timeSlotLabel.setObjectName("timeSlotLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.timeSlotLabel)
        self.timeSlot = QtWidgets.QListWidget(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.timeSlot.setFont(font)
        self.timeSlot.setObjectName("timeSlot")
        item = QtWidgets.QListWidgetItem()
        self.timeSlot.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.timeSlot.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.timeSlot.addItem(item)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeSlot)
        self.facilitiesLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.facilitiesLabel.setFont(font)
        self.facilitiesLabel.setObjectName("facilitiesLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.facilitiesLabel)
        self.libraryCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.libraryCheckBox.setMinimumSize(QtCore.QSize(260, 17))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.libraryCheckBox.setFont(font)
        self.libraryCheckBox.setObjectName("libraryCheckBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.libraryCheckBox)
        self.computerCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.computerCheckBox.setMinimumSize(QtCore.QSize(260, 17))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.computerCheckBox.setFont(font)
        self.computerCheckBox.setObjectName("computerCheckBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.computerCheckBox)
        self.okButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.okButton)
        self.closeButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.closeButton.setObjectName("closeButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.closeButton)
        self.label = QtWidgets.QLabel(StudentDetails)
        self.label.setGeometry(QtCore.QRect(130, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.uploadPicBtn = QtWidgets.QPushButton(StudentDetails)
        self.uploadPicBtn.setGeometry(QtCore.QRect(410, 60, 81, 23))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.uploadPicBtn.setFont(font)
        self.uploadPicBtn.setObjectName("uploadPicBtn")
        self.picView = QtWidgets.QLabel(StudentDetails)
        self.picView.setGeometry(QtCore.QRect(410, 100, 111, 122))
        self.picView.setText("")
        self.picView.setObjectName("picView")

        self.retranslateUi(StudentDetails)
        self.timeSlot.setCurrentRow(0)
        self.closeButton.clicked.connect(StudentDetails.close)
        QtCore.QMetaObject.connectSlotsByName(StudentDetails)

    def retranslateUi(self, StudentDetails):
        _translate = QtCore.QCoreApplication.translate
        StudentDetails.setWindowTitle(_translate("StudentDetails", "Student Details"))
        self.nameLabel.setText(_translate("StudentDetails", "Name"))
        self.ageLabel.setText(_translate("StudentDetails", "Age"))
        self.addressLabel.setText(_translate("StudentDetails", "Address"))
        self.genderLabel.setText(_translate("StudentDetails", "Gender"))
        self.maleRadioButton.setText(_translate("StudentDetails", "Male"))
        self.femaleRadioButton.setText(_translate("StudentDetails", "Female"))
        self.courseLabel.setText(_translate("StudentDetails", "Course"))
        self.courseList.setItemText(0, _translate("StudentDetails", "----------Select-------"))
        self.courseList.setItemText(1, _translate("StudentDetails", "Software Engineering"))
        self.courseList.setItemText(2, _translate("StudentDetails", "Software Systems Design"))
        self.courseList.setItemText(3, _translate("StudentDetails", "Software Testing"))
        self.courseList.setItemText(4, _translate("StudentDetails", "Java Development"))
        self.courseList.setItemText(5, _translate("StudentDetails", "Web Development"))
        self.timeSlotLabel.setText(_translate("StudentDetails", "Time Slot"))
        self.timeSlot.setSortingEnabled(False)
        __sortingEnabled = self.timeSlot.isSortingEnabled()
        self.timeSlot.setSortingEnabled(False)
        item = self.timeSlot.item(0)
        item.setText(_translate("StudentDetails", "07:00-09:00"))
        item = self.timeSlot.item(1)
        item.setText(_translate("StudentDetails", "09:00-11:00"))
        item = self.timeSlot.item(2)
        item.setText(_translate("StudentDetails", "11:00-01:00"))
        self.timeSlot.setSortingEnabled(__sortingEnabled)
        self.facilitiesLabel.setText(_translate("StudentDetails", "Facilities"))
        self.libraryCheckBox.setText(_translate("StudentDetails", "Library"))
        self.computerCheckBox.setText(_translate("StudentDetails", "Computer"))
        self.okButton.setText(_translate("StudentDetails", "OK"))
        self.closeButton.setText(_translate("StudentDetails", "Close"))
        self.label.setText(_translate("StudentDetails", "Accept Student Data"))
        self.uploadPicBtn.setText(_translate("StudentDetails", "Upload Picture"))


