# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/StudentDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_studentDashboard(object):
    def setupUi(self, studentDashboard):
        studentDashboard.setObjectName("studentDashboard")
        studentDashboard.resize(969, 764)
        self.centralwidget = QtWidgets.QWidget(studentDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.studentLabel = QtWidgets.QLabel(self.centralwidget)
        self.studentLabel.setGeometry(QtCore.QRect(10, 10, 871, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.studentLabel.setFont(font)
        self.studentLabel.setObjectName("studentLabel")
        self.personalDetailsLabel = QtWidgets.QTabWidget(self.centralwidget)
        self.personalDetailsLabel.setGeometry(QtCore.QRect(10, 50, 881, 581))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.personalDetailsLabel.setFont(font)
        self.personalDetailsLabel.setIconSize(QtCore.QSize(20, 16))
        self.personalDetailsLabel.setObjectName("personalDetailsLabel")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 101, 41))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 101, 41))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(130, 140, 101, 41))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(130, 190, 291, 41))
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(130, 240, 101, 41))
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(130, 290, 391, 41))
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 340, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(130, 340, 101, 41))
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(130, 380, 301, 41))
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(130, 0, 101, 41))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setObjectName("label_18")
        self.printButton = QtWidgets.QPushButton(self.tab)
        self.printButton.setGeometry(QtCore.QRect(10, 440, 101, 41))
        self.printButton.setObjectName("printButton")
        self.picView = QtWidgets.QLabel(self.tab)
        self.picView.setGeometry(QtCore.QRect(320, 10, 111, 122))
        self.picView.setText("")
        self.picView.setObjectName("picView")
        self.personalDetailsLabel.addTab(self.tab, "")
        self.timeTableTab = QtWidgets.QWidget()
        self.timeTableTab.setObjectName("timeTableTab")
        self.timeTableView = QtWidgets.QTableWidget(self.timeTableTab)
        self.timeTableView.setGeometry(QtCore.QRect(10, 10, 791, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeTableView.sizePolicy().hasHeightForWidth())
        self.timeTableView.setSizePolicy(sizePolicy)
        self.timeTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.timeTableView.setObjectName("timeTableView")
        self.timeTableView.setColumnCount(4)
        self.timeTableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timeTableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timeTableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timeTableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timeTableView.setHorizontalHeaderItem(3, item)
        self.printButton_2 = QtWidgets.QPushButton(self.timeTableTab)
        self.printButton_2.setGeometry(QtCore.QRect(10, 470, 101, 41))
        self.printButton_2.setObjectName("printButton_2")
        self.personalDetailsLabel.addTab(self.timeTableTab, "")
        studentDashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(studentDashboard)
        self.statusbar.setObjectName("statusbar")
        studentDashboard.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(studentDashboard)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        studentDashboard.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(studentDashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        studentDashboard.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(studentDashboard)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_toolbar = QtWidgets.QAction(studentDashboard)
        self.actionExit_toolbar.setObjectName("actionExit_toolbar")
        self.actionLogout = QtWidgets.QAction(studentDashboard)
        self.actionLogout.setObjectName("actionLogout")
        self.actionDetails = QtWidgets.QAction(studentDashboard)
        self.actionDetails.setObjectName("actionDetails")
        self.toolBar.addAction(self.actionDetails)
        self.toolBar.addAction(self.actionLogout)
        self.toolBar.addAction(self.actionExit_toolbar)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(studentDashboard)
        self.personalDetailsLabel.setCurrentIndex(1)
        self.actionExit.triggered.connect(studentDashboard.close)
        self.actionExit_toolbar.triggered.connect(studentDashboard.close)
        QtCore.QMetaObject.connectSlotsByName(studentDashboard)

    def retranslateUi(self, studentDashboard):
        _translate = QtCore.QCoreApplication.translate
        studentDashboard.setWindowTitle(_translate("studentDashboard", "Student Dashboard"))
        self.studentLabel.setText(_translate("studentDashboard", "Welcome"))
        self.label.setText(_translate("studentDashboard", "ID:"))
        self.label_2.setText(_translate("studentDashboard", "23444445435"))
        self.label_3.setText(_translate("studentDashboard", "Name:"))
        self.label_4.setText(_translate("studentDashboard", "23444445435"))
        self.label_5.setText(_translate("studentDashboard", "Age:"))
        self.label_6.setText(_translate("studentDashboard", "23444445435"))
        self.label_7.setText(_translate("studentDashboard", "Address:"))
        self.label_8.setText(_translate("studentDashboard", "23444445435"))
        self.label_9.setText(_translate("studentDashboard", "23444445435"))
        self.label_10.setText(_translate("studentDashboard", "Gender:"))
        self.label_11.setText(_translate("studentDashboard", "Course:"))
        self.label_12.setText(_translate("studentDashboard", "23444445435"))
        self.label_13.setText(_translate("studentDashboard", "Time Slot:"))
        self.label_14.setText(_translate("studentDashboard", "23444445435"))
        self.label_15.setText(_translate("studentDashboard", "Facilities:"))
        self.label_16.setText(_translate("studentDashboard", "Facilities:"))
        self.label_17.setText(_translate("studentDashboard", "Type:"))
        self.label_18.setText(_translate("studentDashboard", "Student"))
        self.printButton.setText(_translate("studentDashboard", "Print"))
        self.personalDetailsLabel.setTabText(self.personalDetailsLabel.indexOf(self.tab), _translate("studentDashboard", "Personal Details"))
        item = self.timeTableView.horizontalHeaderItem(0)
        item.setText(_translate("studentDashboard", "Course Code"))
        item = self.timeTableView.horizontalHeaderItem(1)
        item.setText(_translate("studentDashboard", "Course Title"))
        item = self.timeTableView.horizontalHeaderItem(2)
        item.setText(_translate("studentDashboard", "Time"))
        item = self.timeTableView.horizontalHeaderItem(3)
        item.setText(_translate("studentDashboard", "Day"))
        self.printButton_2.setText(_translate("studentDashboard", "Print"))
        self.personalDetailsLabel.setTabText(self.personalDetailsLabel.indexOf(self.timeTableTab), _translate("studentDashboard", "Time Table"))
        self.toolBar.setWindowTitle(_translate("studentDashboard", "toolBar"))
        self.menuFile.setTitle(_translate("studentDashboard", "File"))
        self.menuTools.setTitle(_translate("studentDashboard", "Tools"))
        self.actionExit.setText(_translate("studentDashboard", "Exit"))
        self.actionExit.setShortcut(_translate("studentDashboard", "Alt+X"))
        self.actionExit_toolbar.setText(_translate("studentDashboard", "Exit"))
        self.actionExit_toolbar.setToolTip(_translate("studentDashboard", "Exit"))
        self.actionExit_toolbar.setShortcut(_translate("studentDashboard", "Alt+X"))
        self.actionLogout.setText(_translate("studentDashboard", "Logout"))
        self.actionDetails.setText(_translate("studentDashboard", "Details"))


