# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/UserForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserForm(object):
    def setupUi(self, UserForm):
        UserForm.setObjectName("UserForm")
        UserForm.resize(426, 284)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        UserForm.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(UserForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 60, 311, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.courseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.courseLabel.setFont(font)
        self.courseLabel.setObjectName("courseLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.courseLabel)
        self.userType = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.userType.setFont(font)
        self.userType.setObjectName("userType")
        self.userType.addItem("")
        self.userType.addItem("")
        self.userType.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userType)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.addressLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.addressLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.loginIdLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.loginIdLineEdit.setFont(font)
        self.loginIdLineEdit.setObjectName("loginIdLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.loginIdLineEdit)
        self.genderLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.genderLabel_2.setFont(font)
        self.genderLabel_2.setObjectName("genderLabel_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.genderLabel_2)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.okButton = QtWidgets.QPushButton(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.okButton.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.okButton)
        self.closeButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.closeButton)
        self.label = QtWidgets.QLabel(UserForm)
        self.label.setGeometry(QtCore.QRect(130, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(UserForm)
        self.closeButton.clicked.connect(UserForm.close)
        QtCore.QMetaObject.connectSlotsByName(UserForm)

    def retranslateUi(self, UserForm):
        _translate = QtCore.QCoreApplication.translate
        UserForm.setWindowTitle(_translate("UserForm", "Activate User"))
        self.courseLabel.setText(_translate("UserForm", "User Type"))
        self.userType.setItemText(0, _translate("UserForm", "----------Select-------"))
        self.userType.setItemText(1, _translate("UserForm", "Student"))
        self.userType.setItemText(2, _translate("UserForm", "Faculty"))
        self.addressLabel.setText(_translate("UserForm", "User ID:"))
        self.ageLabel.setText(_translate("UserForm", "Email:"))
        self.genderLabel.setText(_translate("UserForm", "Login ID"))
        self.genderLabel_2.setText(_translate("UserForm", "Password:"))
        self.okButton.setText(_translate("UserForm", "Activate"))
        self.closeButton.setText(_translate("UserForm", "Cancel"))
        self.label.setText(_translate("UserForm", "Activate User"))


